/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-05-11 14:28:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import restaurant.*;
import java.util.*;

public final class ViewAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("restaurant");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset = \"UTF-8\">\n");
      out.write("\t\t<title>Inicio</title>\n");
      out.write("\t\t\t\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" integrity=\"sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t.trwhite{\n");
      out.write("\t\t\t\tbackground: white;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.bt{\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tmargin-left:8%;\n");
      out.write("\t\t\t    padding:5px 15px;\n");
      out.write("\t\t\t    background:#7eb9dc;\n");
      out.write("\t\t\t    border:0 none;\n");
      out.write("\t\t\t    border-radius: 7px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.tlt{\n");
      out.write("\t\t\t\tpadding: 1%;\n");
      out.write("\t\t\t\ttext-align: center;\n");
      out.write("\t\t\t\tbackground: rgba(255,255,255,0.7);\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t.ctr{\n");
      out.write("\t\t\t\ttext-align: center;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</style>\n");
      out.write("\t</head>\n");
      out.write("\t<body background = \"prueba.jpg\" width = \"100%\" heigth = \"100%\">\n");
      out.write("\n");
      out.write("\t\t");
 ArrayList<Restaurant> restaurantslist = (ArrayList<Restaurant>) session.getAttribute("restaurants"); 
      out.write('\n');
      out.write('	');
      out.write('	');
 ArrayList<ArrayList<Order>> ordersallrest = (ArrayList<ArrayList<Order>>) session.getAttribute("ordersallrest"); 
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
 for(int i = 0; i<restaurantslist.size();i++) { 
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<h2 class = \"tlt\"> <a href = \"/proyecto/rest?id=");
      out.print(restaurantslist.get(i).getIdRest());
      out.write('"');
      out.write('>');
      out.print( restaurantslist.get(i).getNameRest() );
      out.write(',');
      out.write(' ');
      out.print(restaurantslist.get(i).getAddressRest() );
      out.write("</a></h2>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t<table class=\"table ctr\">\n");
      out.write("\t\t\t\t\t<thead class=\"thead-dark\">\n");
      out.write("\t\t\t\t\t\t<tr class = \"trwhite\">\n");
      out.write("\t\t\t\t\t\t\t<th> Pedido </th>\n");
      out.write("\t\t\t\t\t\t\t<th> Fecha y Hora última actualización </th>\n");
      out.write("\t\t\t\t\t\t\t<th> Estado </th>\n");
      out.write("\t\t\t\t\t\t\t<th> Total </th>\n");
      out.write("\t\t\t\t\t\t\t<th>\t</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t");
 for(int j = 0; j< ordersallrest.get(i).size(); j++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<tr class = \"trwhite\">\n");
      out.write("\t\t\t\t\t\t\t\t<td> <a href = \"seeorder?id=");
      out.print(ordersallrest.get(i).get(j).getIdOrder());
      out.write('"');
      out.write('>');
      out.print( ordersallrest.get(i).get(j).getIdOrder() );
      out.write("</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td> ");
      out.print( ordersallrest.get(i).get(j).getFechaHora() );
      out.write(" </td>  \n");
      out.write("\t\t\t\t\t\t\t\t<td> ");
      out.print( ordersallrest.get(i).get(j).getState() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t<td> ");
      out.print( ordersallrest.get(i).get(j).getPrecioTotal() );
      out.write(" € </td>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<td> \n");
      out.write("\t\t\t\t\t\t\t\t<form action = \"changestate\">\n");
      out.write("\t\t\t\t\t\t\t\t \t<label for = \"unittype\"> Cambiar estado a: <br> </label> \n");
      out.write("\t\t\t\t\t\t\t\t\t <select id\"idstate\" data-toggle=\"dropdown\" class=\"btn btn-secondary dropdown-toggle\" name = \"state\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t \t<option value = \"term\"  name = \"term\">terminated </option>\n");
      out.write("\t\t\t\t\t\t\t\t\t \t<option value = \"ready\"  name = \"ready\">ready</option> \n");
      out.write("\t\t\t\t\t\t\t\t\t \t<option value = \"deliver\"  name= \"deliver\">on deliver</option> \n");
      out.write("\t\t\t\t\t\t\t\t\t \t<option value = \"inprogress\"  name = \"inprogress\">in progress</option> \n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type = \"hidden\" name = \"idorder\" value = \"");
      out.print(ordersallrest.get(i).get(j).getIdOrder());
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type = \"submit\" class = \"bt\" name = \"edit\" value = \"Editar Pedido\"> </td>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\t \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t<form action = \"close\">\n");
      out.write("\t\t\t\t<input type = \"submit\" class=\"btn btn-danger\"  name = \"close\" value = \"Cerrar sesión\"> \n");
      out.write("\t\t\t</form>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
