/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-05-11 11:15:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import restaurant.*;
import java.util.*;

public final class ViewRestaurantUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("restaurant");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write(" <script src=\"add.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset = \"UTF-8\">\n");
      out.write("\t\t<title>Carta</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" integrity=\"sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB\" crossorigin=\"anonymous\">\n");
      out.write("\t\t<style type=\"text/css\"> \n");
      out.write("\t\t\t.ctr { \n");
      out.write("\t\t\t\ttext-align: center;\n");
      out.write("\t\t\t\tfont-size: 50px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.img-css{\n");
      out.write("\t\t\t\tmax-width: 50%;\n");
      out.write("\t\t\t\tmargin-left: 25%;\n");
      out.write("\t\t\t\tborder-radius: 30px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.centre{\t\n");
      out.write("\t\t\t\tpadding: -25%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.boxctr{\n");
      out.write("\t\t\t\tmargin-left: 37%;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.in{\n");
      out.write("\t\t\t\tmargin: .3em 47px;\n");
      out.write("\t\t\t\tborder-radius: 7px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tinput[type = \"text\"]{\n");
      out.write("\t\t\t\tborder:2px solid #7eb9dc;\n");
      out.write("\t\t\t\tpadding:3px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tinput[type = \"tel\"]{\n");
      out.write("\t\t\t\tborder:2px solid #7eb9dc;\n");
      out.write("\t\t\t\tpadding:3px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.inb{\n");
      out.write("\t\t\t\tmargin: .3em 75px;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t.fond{\n");
      out.write("\t\t\t\tbackground: #c89048;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</style>\n");
      out.write("\t</head>\n");
      out.write("\t<body id = \"result\" >\n");
      out.write("\t\t");
 ArrayList<Plato> cart = (ArrayList<Plato>) request.getAttribute("cart"); 
      out.write('\n');
      out.write('	');
      out.write('	');
 User user = (User) session.getAttribute("user"); 
      out.write('\n');
      out.write('	');
      out.write('	');
 String ciudad = (String) request.getAttribute("cit"); 
      out.write('\n');
      out.write('	');
      out.write('	');
 int id_rest = (int) request.getAttribute("id_rest"); 
      out.write("\n");
      out.write("\t\t<form action = \"init\">\n");
      out.write("\t\t\t\t<input type = \"submit\" class = \"btn btn-danger\" value = \"Volver al inicio\">\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<img src=\"chameli_dallas_menu.png\" class=\"img-rounded img-css\" height = \"300px\" width =\"70%\">\n");
      out.write("\t\t<form>\n");
      out.write("\t\t\t<input type = \"hidden\" class = \"idrest\" id = \"");
      out.print(id_rest);
      out.write("\">\n");
      out.write("\t\t\t<input type = \"hidden\" class = \"ciudadpedido\" id = \"");
      out.print( ciudad );
      out.write("\">\n");
      out.write("\t\t\t<table class=\"table table-hover\">\n");
      out.write("\t\t\t\t<thead class=\"thead-dark\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th> Plato </th>\n");
      out.write("\t\t\t\t\t\t<th> Descripción</th>\n");
      out.write("\t\t\t\t\t\t<th> Precio </th>\n");
      out.write("\t\t\t\t\t\t<th></th>\n");
      out.write("\t\t\t\t\t\t<th></th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</thead>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t");
 for(int i = 0; i< cart.size(); i++){ 
      out.write("\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td> ");
      out.print( cart.get(i).getNamePlate() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t<td> ");
      out.print( cart.get(i).getDescripcion() );
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t<td> ");
      out.print( cart.get(i).getPrecio() );
      out.write(" € </td>\n");
      out.write("\t\t\t\t\t\t<td><input type = \"button\" class = \"boton btn btn-success\" name = \"");
      out.print(cart.get(i).getNamePlate());
      out.write("\" id = \"");
      out.print(cart.get(i).getIdPlato());
      out.write("\" value = \"+\" > </td>\n");
      out.write("\t\t\t\t\t\t<td><input type = \"button\" class = \"botonminus btn btn-danger\" name = \"");
      out.print(cart.get(i).getNamePlate());
      out.write("\" id = \"");
      out.print(cart.get(i).getIdPlato());
      out.write("\" value = \"-\" > </td>\n");
      out.write("\t\t\t\t\t\t<input type = \"hidden\" class = \"");
      out.print(cart.get(i).getNamePlate());
      out.write("\" value = \"");
      out.print( cart.get(i).getPrecio() );
      out.write("\">\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<h4> TOTAL DEL PEDIDO </h4>\n");
      out.write("\t\t<table id =\"totalpedido\" class=\"table table-hover\">\n");
      out.write("\t\t\t<thead class=\"thead-dark\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th> Producto </th>\n");
      out.write("\t\t\t\t\t<th> Unidades </th>\n");
      out.write("\t\t\t\t\t<th> Precio </th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t<tr id=\"total\">\n");
      out.write("          \t\t\t\t<td>Total:</td>\n");
      out.write("          \t\t\t\t\t<td></td>\n");
      out.write("          \t\t\t\t<td id=\"totalval\">0.00 €</td>\n");
      out.write("        \t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t</table>\t\n");
      out.write("\n");
      out.write("\t\t<div class = \"fond\">\n");
      out.write("\t\t\t<h2 class = \"ctr\"> DIRECCIÓN DE ENTREGA </h2>\n");
      out.write("\t\t\t<div class = \"boxctr\">\n");
      out.write("\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<label class = \"in\"> Dirección:  </label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<input type = \"text\" name = \"street\" class = \"in\" id = \"str\" value = \"");
      out.print(user.getAddress());
      out.write("\" required> \n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<label class = \"in\"> Ciudad: </label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<input type = \"text\" name = \"city\" class = \"in\" id = \"cit\" value = \"");
      out.print(user.getCiudad());
      out.write("\" required>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<label class = \"in\"> Número de telefono: </label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<input type = \"tel\" name = \"tele\" class = \"in\" id = \"tlf\" value = \"");
      out.print(user.getPhone());
      out.write("\"required>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div >\n");
      out.write("\t\t\t\t\t\t<input type  =\"button\" class = \"inb butform btn btn-success\" value = \"Hacer pedido\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
